#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SERIES_START = "2026-07-01T00:00:00+05:30";
const SERIES_TOTAL = 108;
const TIMEZONE = "Asia/Kolkata";
const DAY_MS = 86_400_000;

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const START_MS = Date.parse(SERIES_START);

function startOfDay(date) {
  const ymd = new Intl.DateTimeFormat("en-CA", {
    timeZone: TIMEZONE,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);
  return Date.parse(`${ymd}T00:00:00+05:30`);
}

function unlockedCount(now = new Date()) {
  const daysElapsed = Math.floor((startOfDay(now) - START_MS) / DAY_MS);
  return Math.max(0, Math.min(SERIES_TOTAL, daysElapsed + 1));
}

function publishLimit() {
  const override = process.env.PB_MAX_N;
  if (override === undefined) return unlockedCount();
  if (!/^\d+$/.test(override)) {
    throw new Error(`PB_MAX_N must be a whole number, got "${override}"`);
  }
  return Math.min(Number(override), SERIES_TOTAL);
}

function stripLineComment(line) {
  let out = "";
  for (let i = 0; i < line.length; i++) {
    if (line[i] === "\\") {
      out += line.slice(i, i + 2);
      i++;
    } else if (line[i] === "%") {
      break;
    } else {
      out += line[i];
    }
  }
  return out.trimEnd();
}

function stripComments(tex) {
  return tex.replace(/\r\n/g, "\n").split("\n").map(stripLineComment).join("\n");
}

function readGroup(text, openBrace) {
  let depth = 1;
  let i = openBrace + 1;
  for (; i < text.length && depth > 0; i++) {
    if (text[i] === "\\") i++;
    else if (text[i] === "{") depth++;
    else if (text[i] === "}" && --depth === 0) break;
  }
  return { inner: text.slice(openBrace + 1, i), end: i + 1 };
}

function readProblem(tex, file) {
  const src = tex.trim();
  if (!src) return null;

  const begin = /\\begin\{problem\}\s*\{/.exec(src);
  if (!begin) throw new Error(`${file}: expected \\begin{problem}{Title}`);

  const { inner, end } = readGroup(src, begin.index + begin[0].length - 1);
  const close = src.indexOf("\\end{problem}", end);
  if (close === -1) throw new Error(`${file}: missing \\end{problem}`);

  const title = inner.trim();
  const body = src.slice(end, close).trim();
  if (!title) throw new Error(`${file}: problem has an empty title`);
  if (!body) throw new Error(`${file}: problem has an empty body`);

  return { title, body };
}

function collectProblems(limit) {
  const problems = [];
  for (let n = 1; n <= limit; n++) {
    const file = `p${String(n).padStart(3, "0")}.tex`;
    let tex;
    try {
      tex = readFileSync(join(ROOT, "problems", file), "utf8");
    } catch {
      continue;
    }
    const problem = readProblem(stripComments(tex), file);
    if (problem) problems.push({ n, ...problem });
  }
  return problems;
}

const limit = publishLimit();
const problems = collectProblems(limit);

writeFileSync(
  join(ROOT, "data", "problems.js"),
  `/* Generated by scripts/build.mjs — do not edit by hand.
 * Statements come from problems/p###.tex; regenerate with: node scripts/build.mjs
 */
"use strict";

var SERIES_START_MS = ${START_MS};
var SERIES_TOTAL = ${SERIES_TOTAL};

var PROBLEMS = ${JSON.stringify(problems, null, 2)};
`,
  "utf8",
);

console.log(
  `data/problems.js — ${problems.length} of ${SERIES_TOTAL} problems (unlocked through ${limit})`,
);
